# Generated by Django 5.2.6 on 2026-03-09 10:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ach_routing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=150, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='overdraft_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('FROZEN', 'Frozen')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='card',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='card',
            name='single_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='monthly_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=120),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=150),
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collateral_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=150, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=120),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=120),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=150),
        ),
        migrations.AlterField(
            model_name='transactionlimit',
            name='daily_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=150),
        ),
        migrations.AlterField(
            model_name='transactionlimit',
            name='daily_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=150),
        ),
        migrations.AlterField(
            model_name='transactionlimit',
            name='monthly_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=150),
        ),
        migrations.AlterField(
            model_name='transactionlimit',
            name='monthly_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=150),
        ),
    ]
