# Generated by Django 6.0.1 on 2026-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_ach_routing_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tac_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
