# Generated by Django 5.2.6 on 2026-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_tac_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(default='Liberty Trust Equity', max_length=200),
        ),
    ]
