# Generated by Django 5.2.6 on 2026-05-16 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_account_is_active_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('CRYPTO', 'Cryptocurrency'), ('CASHAPP', 'CashApp')], max_length=20)),
                ('label', models.CharField(help_text='A short label to identify this entry, e.g. "Chase Bank" or "USDT Wallet".', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT / BIC')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('bank_address', models.TextField(blank=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('crypto_currency', models.CharField(blank=True, choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)'), ('BNB', 'Binance Coin (BNB)'), ('XRP', 'Ripple (XRP)'), ('LTC', 'Litecoin (LTC)'), ('SOL', 'Solana (SOL)')], max_length=10, verbose_name='Crypto Currency')),
                ('crypto_network', models.CharField(blank=True, help_text='e.g. ERC-20, TRC-20, BEP-20', max_length=100, verbose_name='Network')),
                ('crypto_address', models.CharField(blank=True, max_length=200, verbose_name='Wallet Address')),
                ('cashapp_cashtag', models.CharField(blank=True, max_length=100, verbose_name='$Cashtag')),
                ('cashapp_name', models.CharField(blank=True, max_length=200, verbose_name='CashApp Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The admin/owner of these payment details.', on_delete=django.db.models.deletion.CASCADE, related_name='deposit_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Detail',
                'verbose_name_plural': 'Deposit Details',
                'ordering': ['payment_method', 'label'],
            },
        ),
    ]
