# Generated by Django 5.2.6 on 2026-07-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_depositdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_receive_tac_mail',
            field=models.BooleanField(default=False, help_text='If enabled, the user is emailed their Transfer Authorization Code whenever it is generated.'),
        ),
    ]
