# Generated by Django 5.2.6 on 2026-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_can_receive_tac_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plantext_plain',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Plain Text Test'),
        ),
    ]
