# Generated by Django 5.2.6 on 2026-08-06 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_plantext_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
