# Generated by Django 6.0.5 on 2026-09-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance_before',
        ),
    ]
