# Generated by Django 5.2.6 on 2026-09-27 01:34

import django.utils.timezone
from django.db import migrations, models


def sync_account_currency(apps, schema_editor):
    """Set every existing account's currency to its owner's preferred currency."""
    Account = apps.get_model('app', 'Account')
    for account in Account.objects.select_related('customer').only('id', 'currency', 'customer__preferred_currency'):
        if account.currency != account.customer.preferred_currency:
            Account.objects.filter(pk=account.pk).update(currency=account.customer.preferred_currency)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rebrand_account_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', editable=False, max_length=3),
        ),
        migrations.RunPython(sync_account_currency, migrations.RunPython.noop),
    ]
