# Generated by Django 5.2.6 on 2026-09-27 02:18

import app.fields
from django.db import migrations
from django.db.models import Q


def encrypt_existing(apps, schema_editor):
    """Re-save stored numbers so plain-text values from before this migration get encrypted."""
    CustomUser = apps.get_model('app', 'CustomUser')
    users = CustomUser.objects.filter(Q(ssn__isnull=False) | Q(tax_identity_number__isnull=False))
    for user in users.only('id', 'ssn', 'tax_identity_number').iterator():
        # Loading decrypts (or passes plain text through); saving always encrypts
        CustomUser.objects.filter(pk=user.pk).update(ssn=user.ssn, tax_identity_number=user.tax_identity_number)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ssn',
            field=app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_identity_number',
            field=app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
