# Generated by Django 5.2.6 on 2026-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_encrypt_ssn_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pay_by_bank_transfer',
            field=models.BooleanField(default=True, verbose_name='Bank Transfer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pay_by_online_payment',
            field=models.BooleanField(default=True, verbose_name='Online Payment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pay_by_wire_transfer',
            field=models.BooleanField(default=True, verbose_name='Wire Transfer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pay_in_branch',
            field=models.BooleanField(default=False, verbose_name='Payment in Branch'),
        ),
    ]
