# Generated by Django 5.2.6 on 2026-10-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_activation_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('LOGIN_FAILED', 'Login Failed'), ('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], max_length=20),
        ),
    ]
