# Generated by Django 5.2.6 on 2026-10-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auditlog_login_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile App'), ('ATM', 'ATM'), ('BRANCH', 'Branch'), ('API', 'API'), ('CRYPTO', 'Crypto Currencies')], default='WEB', max_length=20),
        ),
    ]
